spring:
  datasource:
    platform: h2
    url: jdbc:h2:file:~/h2/jpa;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE
    username: jpa
    password: jpaP@ssw0rd
  jpa:
    database-platform: h2
    show-sql: true
    hibernate:
      ddl-auto: create
    generate-ddl: true
    properties:
      hibernate.format_sql: true
logging:
  level:
    com.ming.jpa-study: debug
    org:
      hibernate:
        type: trace
        SQL: debug
